# Generated by Django 5.2.4 on 2025-07-22 18:10

import catalog.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[catalog.validators.validate_file_size], verbose_name='profile_picture'),
        ),
    ]
