# Generated by Django 5.2.4 on 2025-07-22 18:10

import catalog.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[catalog.validators.validate_file_size], verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[catalog.validators.validate_file_size], verbose_name='cover_image'),
        ),
    ]
