# Generated by Django 5.2.4 on 2025-07-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='users.member'),
        ),
        migrations.AddField(
            model_name='fine',
            name='borrow_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='circulation.borrowrecord'),
        ),
    ]
