# Generated by Django 5.2.4 on 2025-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='due_date',
        ),
    ]
