# Generated by Django 5.2.4 on 2025-07-21 17:38

import circulation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_remove_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(default=circulation.models.default_due_date),
        ),
    ]
