# Generated by Django 5.2.4 on 2025-07-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_borrowrecord_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
